#!/sbin/runscript

start() {
  ebegin "Starting Denon Connection Multiplexer"
  start-stop-daemon --start --make-pidfile --pidfile /var/run/denon-multiplexd.pid -1 /dev/null -2 /dev/null --quiet --user nobody --background --exec /usr/sbin/denon-multiplexd ${receiver_address}
  eend $?
}

stop() {
  ebegin "Stopping Denon Connection Multiplexer"
  start-stop-daemon --stop --pidfile /var/run/denon-multiplexd.pid --quiet --exec /usr/sbin/denon-multiplexd
  eend $?
}
